# downloads model parameters
# p1 GAN model
gdown -O ./p1_scratch_model.ckpt https://drive.google.com/u/0/uc?id=1ZxVpbAfmqZCvleB5bJaYWBLocehx4smk&export=download
# p2 Diffusion model
gdown -O ./p2_scratch_model.ckpt https://drive.google.com/u/0/uc?id=1_GpHc9LJmD5IJiB-5lfUNQHD5zUg2kiY&export=download
# p3 SVHN DANN
gdown -O ./p3_SVHN_DANN.ckpt https://drive.google.com/u/3/uc?id=1bsg9y8boy1qSk0Ex8inwkri5zLR0EtUD&export=download
# p3 USPS DANN
gdown -O ./p3_USPS_DANN.ckpt https://drive.google.com/u/3/uc?id=1-0J6lACIy9A6k3eC2zSJ3KPFpsjr4aSK&export=download